export default {
  ad_index: "/pages/ad/index",
  address_details_index: "/pages/address/details/index",
  address_index: "/pages/address/index",
  cart_index: "/pages/cart/index",
  classify_index: "/pages/classify/index",
  demo_index: "/pages/demo/index",
  goods_index: "/pages/goods/index",
  home_index: "/pages/home/index",
  login_index: "/pages/login/index",
  mine_index: "/pages/mine/index",
  order_index: "/pages/order/index",
  search_index: "/pages/search/index",
  webview_index: "/pages/webview/index",
}
